name: 'AWS EKS kubectl Actions'
author: ravinayag
description: An GitHub Action allowing you to integrate AWS EKS via kubectl

branding:
  color: 'black'
  icon: 'command'
runs:
  using: 'docker'
  image: 'Dockerfile'
